// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . f . . . 
. . . . f 7 f . . 
. . . f 7 7 7 f . 
. . f 7 7 7 7 7 f 
. f 7 7 7 7 7 7 7 
f 7 7 7 7 7 7 7 7 
f f f f 7 7 7 f f 
. . . f 7 7 7 f . 
. . . f 7 7 7 f . 
`;
            case "image5":
            case "myImage3":return img`
. . . . . f f . . 
. . . . f 6 f . . 
. . . f 6 6 f . . 
. . f 6 6 6 f f f 
. f 6 6 6 6 6 6 6 
f 6 6 6 6 6 6 6 6 
. f 6 6 6 6 6 6 6 
. . f 6 6 6 f f f 
. . . f 6 6 f . . 
`;
            case "image6":
            case "myImage4":return img`
. . . . f f . . . 
. . . . f 2 f . . 
. . . . f 2 2 f . 
f f f f f 2 2 2 f 
f 2 2 2 2 2 2 2 2 
f 2 2 2 2 2 2 2 2 
f 2 2 2 2 2 2 2 2 
f f f f f 2 2 2 f 
. . . . f 2 2 f . 
`;
            case "image7":
            case "myImage5":return img`
. . . f f f f f . 
. . . f 8 8 8 f . 
. . . f 8 8 8 f . 
. . . f 8 8 8 f . 
f f f f 8 8 8 f f 
f 8 8 8 8 8 8 8 8 
. f 8 8 8 8 8 8 8 
. . f 8 8 8 8 8 f 
. . . f 8 8 8 f . 
`;
            case "CmExb+Shr8a3S$CAP0fI":
            case "background":return img`
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
fddddddddddfddddddddddfddddddddddfddddddddddfddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddfddddddddddfddddddddddfddddddddddfddddddddddf
`;
            case "image2":
            case "myImage0":return img`
. . . . . f . . . 
. . . . f 7 f . . 
. . . f 7 7 7 f . 
. . f 7 7 7 7 7 f 
. f 7 7 7 7 7 7 7 
f 7 7 7 7 7 7 7 7 
f f f f 7 7 7 f f 
. . . f 7 7 7 f . 
. . . f 7 7 7 f . 
`;
            case "image8":
            case "myImage6":return img`
. . . f f f f f . 
. . . f 8 8 8 f . 
. . . f 8 8 8 f . 
. . . f 8 8 8 f . 
f f f f 8 8 8 f f 
f 8 8 8 8 8 8 8 8 
. f 8 8 8 8 8 8 8 
. . f 8 8 8 8 8 f 
. . . f 8 8 8 f . 
`;
            case "image3":
            case "myImage1":return img`
. . . . . f f . . 
. . . . f 6 f . . 
. . . f 6 6 f . . 
. . f 6 6 6 f f f 
. f 6 6 6 6 6 6 6 
f 6 6 6 6 6 6 6 6 
. f 6 6 6 6 6 6 6 
. . f 6 6 6 f f f 
. . . f 6 6 f . . 
`;
            case "image4":
            case "myImage2":return img`
. . . . f f . . . 
. . . . f 2 f . . 
. . . . f 2 2 f . 
f f f f f 2 2 2 f 
f 2 2 2 2 2 2 2 2 
f 2 2 2 2 2 2 2 2 
f 2 2 2 2 2 2 2 2 
f f f f f 2 2 2 f 
. . . . f 2 2 f . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
